### ISSUE TITLE
Error Domain=HMErrorDomain Code=66 "The operation couldn’t be completed. (HMErrorDomain error 66.)"

### ISSUE THREAD

**Issue by 128keaton** [KhaosT/HomeKitBridge#9]
Hello again, suddenly my iPhone 4S is throwing this error when I try to add the bridge, any suggestions?

**Comment by Hans-S** [comment]
Heya. I just re-downloaded the demo and the bridge applications. I wanted to see if I can control my lights in my own language now, since Siri speaks Dutch. Of course, this is only in the latest beta. I compiled and ran from the latest Xcode beta, but I also get the OP's error. Have you tested these great apps against the latest beta? The accessory I'm trying to add, when I get the error, looks like this:
![untitled](https://cloud.githubusercontent.com/assets/9403344/6450485/6e9ac3e0-c128-11e4-95ff-8657ae8c8eb4.jpg)
Does that seem right?
Sorry for posting in a closed issue, not sure what the convention is, first post on github
Thanks, Han.s

**Comment by KhaosT** [comment]
If you are trying to add accessory to iOS 8.3b2 (or later), due to the HomeKit specification changes, HomeKit on iOS will reject connecting to accessories created by "HomeKit Accessory Simulator". Since this project uses same framework that powers "HomeKit Accessory Simulator", it no longer works under iOS 8.3b2. Once Apple released a new version of Simulator, I'll make update to this project and get it works with latest spec.

**Comment by nukalaraji** [comment]
Hi,
i tried what you mentioned above and still seeing the issue?i am verifying in the end device.
can you please help?

Ravi

**Comment by KhaosT** [comment]
@nukalaraji Which iOS release are you using right now? iOS 8.3 beta 2 or iOS 8.2?

**Comment by nukalaraji** [comment]
I'm using IOS8.1.2 in my iPad and using Xcode 6.2 with IOS8.2SDK

**Comment by KhaosT** [comment]
@nukalaraji when you try to add accessory, you get an error with error code 66? Can you post the full log from your iOS device?

**Comment by nukalaraji** [comment]
Mar 12 11:25:47 dhcp---20-150 assertiond[826]: assertion failed: 14C1510 12D508: assertiond + 12446 [6756D728-8EE6-3DA2-B069-3EA61C107DF8]: 0x1
Mar 12 11:25:47 dhcp---20-150.SpringBoard[822]: LICreateIconForImage passed NULL CGImageRef image
Mar 12 11:25:47 dhcp---20-150 SpringBoard[822]: ADDING REMOTE com.apple.mobilecal.widget, <BBRemoteDataProvider 0x7f991b348590; com.apple.mobilecal.widget>
Mar 12 11:25:47 dhcp---20-150 SpringBoard[822]: table drop: 101
Mar 12 11:25:47 dhcp---20-150.SpringBoard[822]: Failed to get the user name
Mar 12 11:25:47 dhcp---20-150/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/libexec/lsd[837]: LaunchServices: Failed to set the data protection class for /Users/raviraj/Library/Developer/CoreSimulator/Devices/611E1B6F-8A1F-455B-883D-45C4BFA81883/data/tmp/com.apple.IconsCache/com.apple.mobilecal_CFBundleIcon[31]
Mar 12 11:25:47 dhcp---20-150 SpringBoard[822]: table drop: 101
Mar 12 11:25:47 dhcp---20-150 SpringBoard[822]: SMS Plugin initialized.
Mar 12 11:25:47 dhcp---20-150 SpringBoard[822]: Sharing Plugin initialized.
Mar 12 11:25:47 dhcp---20-150 SpringBoard[822]: Normal message received by listener connection. Ignoring.
Mar 12 11:25:48 dhcp---20-150 HKSample[851]: assertion failed: 14C1510 12D508: libxpc.dylib + 59313 [5775267F-BF6F-33DA-806F-32C27348CDC9]: 0x7d
Mar 12 11:25:48 dhcp---20-150 assertiond[826]: assertion failed: 14C1510 12D508: assertiond + 12446 [6756D728-8EE6-3DA2-B069-3EA61C107DF8]: 0x1
Mar 12 11:25:48 dhcp---20-150 SpringBoard[822]: [MPUSystemMediaControls] Updating supported commands for now playing application.
Mar 12 11:25:48 dhcp---20-150. tccd[845]: Prompting for access to kTCCServiceWillow from /Users/raviraj/Library/Developer/CoreSimulator/Devices/611E1B6F-8A1F-455B-883D-45C4BFA81883/data/Containers/Bundle/Application/F9BC9F3B-ED73-4C98-AB57-1821887D3933/HKSample.app/HKSample
Mar 12 11:25:49 dhcp---20-150. syncdefaultsd[860]: (Note ) SYDAlwaysOnAccount: no account (null)
Mar 12 11:25:49 dhcp---20-150.. syncdefaultsd[860]: (Note ) SYDAccount: no account
Mar 12 11:25:49 dhcp---20-150.. syncdefaultsd[860]: (Note ) SYDPIMAccount: no account (null)
Mar 12 11:25:50 dhcp---20-150.. calaccessd[848]: table drop: 101
Mar 12 11:25:51 dhcp---20-150 homed[861]: objc[861]: Class HMUIndent is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/CoreHAP.framework/CoreHAP and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon. One of the two will be used. Which one is undefined.
Mar 12 11:25:51 dhcp---20-150.. homed[861]: Starting with no existing home data
Mar 12 11:25:51 dhcp---20-150.. homed[861]: Treating OSStatus -25300 (errSecItemNotFound) as Generic error
Mar 12 11:25:51 dhcp---20-150.. securityd[834]:  SOSEngineCreate engine failed load state starting with nothing (null)
Mar 12 11:25:51 dhcp---20-150.. CloudKeychainProxy[862]: start
Mar 12 11:25:51 dhcp---20-150.. CloudKeychainProxy[862]: event -[UbiqitousKVSProxy init] <U----------> start
Mar 12 11:25:51 dhcp---20-150.. homed[861]: Treating OSStatus -25300 (errSecItemNotFound) as Generic error
Mar 12 11:25:51 dhcp---20-150.. CloudKeychainProxy[862]: event -[UbiqitousKVSProxy keybagDidUnlock] <UB--------->
Mar 12 11:25:51 dhcp---20-150.. homed[861]: Treating OSStatus -25300 (errSecItemNotFound) as Generic error
Mar 12 11:25:51 dhcp---20-150.. homed[861]: Accessory manager failed to start discovering accessories for server browser <HAPAccessoryServerBrowserBTLE: 0x7fc752c0f2e0> with error Error Domain=HMErrorDomain Code=48 "Failed to power on Bluetooth because Bluetooth LE is unsupported on this system." UserInfo=0x7fc752c0eed0 {NSLocalizedDescription=Failed to power on Bluetooth because Bluetooth LE is unsupported on this system.}
Mar 12 11:25:51 dhcp---20-150.. CloudKeychainProxy[862]: keytrace -[UbiqitousKVSProxy processKeyChangedEvent:] null:  pending: 
Mar 12 11:25:51 dhcp---20-150.. homed[861]: Treating OSStatus -25300 (errSecItemNotFound) as Generic error
Mar 12 11:25:52 --- last message repeated 1 time ---
Mar 12 11:25:52 dhcp---20-150.. CloudKeychainProxy[862]: event -[UbiqitousKVSProxy timerFired] <UB-Ts------> syncWithPeersPending: 1 inCallout: 0 isLocked: 0
Mar 12 11:25:52 dhcp---20-150.. CloudKeychainProxy[862]: event __39-[UbiqitousKVSProxy doSyncWithAllPeers]_block_invoke_2 <UB--s--C-E-> syncWithAllPeers succeeded
Mar 12 11:25:52 dhcp---20-150.. CloudKeychainProxy[862]: updates SOSCCProcessEnsurePeerRegistration enter SOSCCProcessEnsurePeerRegistration
Mar 12 11:25:52 dhcp---20-150.. CloudKeychainProxy[862]:  __45-[UbiqitousKVSProxy doEnsurePeerRegistration]_block_invoke <UB---e-C---> ensurePeerRegistration called, success ((null))
Mar 12 11:25:53 dhcp---20-150.. syncdefaultsd[860]: (Error) can't find app for bundleID com.apple.security.cloudkeychainproxy3
Mar 12 11:25:53 dhcp---20-150.. syncdefaultsd[860]: (Error) Can't register com.apple.security.cloudkeychainproxy3
Mar 12 11:25:53 dhcp---20-150.. CloudKeychainProxy[862]: NSUbiquitousKeyValueStore error: com.apple.security.cloudkeychainproxy3 has no valid com.apple.developer.ubiquity-kvstore-identifier entitlement
Mar 12 11:25:58 dhcp---20-150.. kbd[865]: table drop: 101
Mar 12 11:26:11 dhcp---20-150.. homed[861]: ### Accessory is missing an Accessory Information Service
Mar 12 11:26:11 dhcp---20-150.. homed[861]: ### Accessory failed _updateForAccessoryInformationService
Mar 12 11:26:11 dhcp---20-150.. homed[861]: ### Accessory failed _updateAndValidateServices
Mar 12 11:26:11 dhcp---20-150.. homed[861]: ### Unable to parse serialized accessory
Mar 12 11:26:11 dhcp---20-150.. homed[861]: [HAP Service Discovery] Failed HAP service discovery on accessory server <HAPAccessoryServerIP: 0x7fc752e0b490>    Device ID: CC:52:AF:C6:D2:D8    Model: - HomeKit Accessory    Protocol Version: 1.0    Source Version: (null)    Config Number: 1    State Number: 1 with error: Error Domain=HMErrorDomain Code=66 "The operation couldn’t be completed. (HMErrorDomain error 66.)"
Mar 12 11:26:12 dhcp---20-150.. homed[861]: Failed to add accessory - HomeKit Accessory with error: Error Domain=HMErrorDomain Code=66 "The operation couldn’t be completed. (HMErrorDomain error 66.)"
Mar 12 11:26:14 dhcp---20-150.. lsd[837]: LaunchServices: Currently 0 installed placeholders: (
)
Mar 12 11:26:24 dhcp---20-150.. mstreamd[815]: (Note ) PS: Media stream daemon stopping.
Mar 12 11:26:24 dhcp---20-150.. mstreamd[815]: (Note ) AS: <MSIOSAlbumSharingDaemon: 0x7fe821c0a980>: Shared Streams daemon has shut down.
Mar 12 11:26:24 dhcp---20-150.. mstreamd[815]: (Warn ) mstreamd: mstreamd shutting down.

**Comment by KhaosT** [comment]
@nukalaraji Did you modified anything in this project...? It seems your bridge doesn't provide the mandatory information service which shouldn't happen if you are using the code in this repo.

**Comment by nukalaraji** [comment]
I've added services into my project. i didn't see this issue before and I'm seeing from last night? don't know why.

**Comment by KhaosT** [comment]
@nukalaraji not sure why that happens. If possible you can upload your code at somewhere and I'll see if I can help on that.
